M48
; DRILL file {KiCad 8.0.7+dfsg-2} date 2024-12-30T00:21:46+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-30T00:21:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7+dfsg-2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X5.525Y-3.41
X6.185Y-4.53
T2
X5.235Y-4.805
X5.235Y-4.905
X6.335Y-4.805
X6.335Y-4.905
M30
